import type { Metadata } from "next";
import { Black_Han_Sans } from "next/font/google";
import "../globals.css";

const black_Han_Sans = Black_Han_Sans({
  subsets: ['latin'],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={black_Han_Sans.className}>{children}</body>
    </html>
  );
}
